[tools]
rust = "latest"

[tasks.clippy]
run = "cargo clippy --all-targets --locked -- -D warnings"

[tasks.fmt]
run = "cargo fmt --all"

[tasks.fmt_check]
run = "cargo fmt --all --check"

[tasks.test]
run = "cargo test --locked"

[tasks.screenshots]
run = "cargo run --example screenshots"
