//! Headless core: the durable task store, its persistence/I-O, and all task
//! mutations. Carries no view, input, or presentation state — operations return
//! structured [`outcome`] values rather than user-facing strings. Both the TUI
//! (`App` wraps a `Store`) and the CLI (`cmd`) drive this type.

use std::path::{Path, PathBuf};

use crate::hooks::{self, HookConfig, HookContext, HookEvent, HookReport};
use crate::todo::{self, Task};

mod archive;
mod external;
mod history;
mod mutations;

pub mod filter;
pub mod outcome;

#[cfg(test)]
pub(crate) mod test_support;

pub use archive::Archive;
pub use history::History;
pub use outcome::{
    AddOutcome, ArchiveDeleteOutcome, ArchiveOutcome, BulkCompleteOutcome, BulkDeleteOutcome,
    CompleteOutcome, DeleteOutcome, DrainReport, EditOutcome, MoveOutcome, PriorityOutcome,
    Reconcile, RenameOutcome, StoreError, TagOutcome, UnarchiveOutcome, UndoOutcome,
};

/// The durable task store. Owns the live task list, the sibling `done.txt`
/// archive, undo history, and the on-disk reconciliation snapshot.
pub struct Store {
    pub(crate) tasks: Vec<Task>,
    pub(crate) history: History,
    pub(crate) archive: Archive,
    pub(crate) file_path: PathBuf,
    /// Snapshot of the file body the last time we read or wrote it; used by
    /// `reconcile` to detect external edits.
    pub(crate) last_disk: String,
    pub(crate) today: String,
    hooks: HookConfig,
    hook_reports: Vec<HookReport>,
}

impl Store {
    /// Construct a store, loading the archive (`done.txt`) off-thread from the
    /// sibling of `file_path`. Used by the TUI so the first frame doesn't wait
    /// on the archive read.
    pub fn new(file_path: PathBuf, body: String, today: String) -> Self {
        let archive = Archive::spawn(&file_path);
        Self::assemble(file_path, archive, body, today)
    }

    /// Like [`Store::new`] but with an explicit `done.txt` path (e.g. from a
    /// `DONE_FILE` env var that isn't a sibling of the todo file).
    pub fn new_with_done(
        file_path: PathBuf,
        done_path: PathBuf,
        body: String,
        today: String,
    ) -> Self {
        let archive = Archive::spawn_at(done_path);
        Self::assemble(file_path, archive, body, today)
    }

    /// Construct a store, loading the sibling archive synchronously (no
    /// background thread). Used by the one-shot CLI.
    pub fn open_sync(file_path: PathBuf, body: String, today: String) -> Self {
        let archive = Archive::load_sync(&file_path);
        Self::assemble(file_path, archive, body, today)
    }

    /// Like [`Store::open_sync`] but with an explicit `done.txt` path.
    pub fn open_sync_with_done(
        file_path: PathBuf,
        done_path: PathBuf,
        body: String,
        today: String,
    ) -> Self {
        let archive = Archive::load_sync_at(done_path);
        Self::assemble(file_path, archive, body, today)
    }

    fn assemble(file_path: PathBuf, archive: Archive, body: String, today: String) -> Self {
        let tasks = todo::parse_file(&body);
        Self {
            tasks,
            history: History::default(),
            archive,
            file_path,
            last_disk: body,
            today,
            hooks: HookConfig::default(),
            hook_reports: Vec::new(),
        }
    }

    pub fn tasks(&self) -> &[Task] {
        &self.tasks
    }

    pub fn archive(&self) -> &Archive {
        &self.archive
    }

    pub fn today(&self) -> &str {
        &self.today
    }

    pub fn file_path(&self) -> &Path {
        &self.file_path
    }

    /// Replace the active post-commit hook settings. Invalid configured paths
    /// are retained so the matching mutation can report a clear warning.
    pub fn set_hooks(&mut self, hooks: HookConfig) {
        self.hooks = hooks;
    }

    /// Clone the active settings when a caller needs to replace this store
    /// while keeping the same process configuration.
    pub fn hooks(&self) -> HookConfig {
        self.hooks.clone()
    }

    /// Drain post-commit reports generated by this store's mutations.
    pub fn take_hook_reports(&mut self) -> Vec<HookReport> {
        std::mem::take(&mut self.hook_reports)
    }

    /// Cloned `raw` for the task at `abs`, or `None` if out of range.
    pub fn task_raw(&self, abs: usize) -> Option<String> {
        self.tasks.get(abs).map(|t| t.raw.clone())
    }

    /// True when at least one live task is marked done.
    pub fn has_completed(&self) -> bool {
        self.tasks.iter().any(|t| t.done)
    }

    /// Update the cached "today". Returns `true` iff the value changed, so the
    /// caller knows to recompute any date-dependent view state.
    pub fn set_today(&mut self, today: String) -> bool {
        if self.today == today {
            return false;
        }
        self.today = today;
        true
    }

    /// Run the hook selected for a committed event and queue a report for the
    /// caller to render. Hook failures never affect the already-committed task
    /// mutation.
    pub(crate) fn post_commit(&mut self, event: HookEvent) {
        let Some(script) = self.hooks.after_mutation.as_deref().map(Path::to_path_buf) else {
            return;
        };
        let context = hook_context(&self.file_path, self.archive.path());
        let report = match context {
            Some(context) => hooks::run(event, &script, &context),
            None => HookReport {
                event,
                script,
                execution: crate::hooks::HookExecution::SpawnFailed,
            },
        };
        self.hook_reports.push(report);
    }
}

fn hook_context(todo_path: &Path, done_path: &Path) -> Option<HookContext> {
    let todo_file = absolute_path(todo_path)?;
    let done_file = absolute_path(done_path)?;
    let root = todo_file.parent()?.to_path_buf();
    Some(HookContext {
        root,
        todo_file,
        done_file,
    })
}

fn absolute_path(path: &Path) -> Option<PathBuf> {
    if path.is_absolute() {
        Some(path.to_path_buf())
    } else {
        std::env::current_dir().ok().map(|cwd| cwd.join(path))
    }
}
